from pydantic import BaseModel, Field, field_validator
from typing import List

class ChatRequest(BaseModel):
    session_id: str = Field(
        ..., 
        min_length=1, 
        max_length=100, 
        description="Unique session identifier."
    )
    query: str = Field(
        ..., 
        min_length=1, 
        max_length=2000, 
        description="The user's question (max 2000 characters)."
    )

    @field_validator('session_id', 'query')
    @classmethod
    def check_not_empty_whitespace(cls, value: str) -> str:
        """Edge Case: Prevent users from sending only spaces or tabs."""
        cleaned_value = value.strip()
        if not cleaned_value:
            raise ValueError("Field cannot be empty or contain only whitespace.")
        return cleaned_value

class SourceCitation(BaseModel):
    filename: str = Field(..., description="The name of the source document.")
    chunk_index: int = Field(..., description="The specific chunk index within the document.")
    text: str = Field(..., description="The raw text snippet retrieved from the vector database.")

class ChatResponse(BaseModel):
    answer: str = Field(..., description="The grounded answer generated by the LLM.")
    sources: List[SourceCitation] = Field(..., description="The context chunks used to generate the answer.")